# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51c481551a7f62323e3d9c22ab2ec28756e23df219cf3788f17469579ab544d506888e0128c3a1a964164959bb2aaff680aa4229f23bc9e41cd45a493a37b5a0

test:
  secret_key_base: 0e62e10653c0fb6952bd2446bb94263d9df76671aa664ddb874f678e4cffbc0d62ce493416a47c55df7dc77d519c2ce742ea822eef6caece6709af07fafc4263

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
